### ISSUE TITLE
Setting: Change "No streams found" message

### ISSUE THREAD

**Issue by flowdee** [flowdee/tomparisde-twitchtv-widget#12]

**Comment by flowdee** [comment]
- https://secure.helpscout.net/conversation/919560186/14165?folderId=407335

**Comment by robertdevore** [comment]
@flowdee Can't see the helpscout link, but I assume by the title it's about needing a setting so admins can type in their own "No streams found" message ... correct?

**Comment by flowdee** [comment]
Yeah indeed

**Comment by flowdee** [comment]
Added with v2.0.4
