### ISSUE TITLE
Embedded Player: Whoops! This embed is misconfigured

### ISSUE THREAD

**Issue by flowdee** [flowdee/tomparisde-twitchtv-widget#24]
`[twitch game="138585" max="1" style="standard" size="large" preview="video"]`

<img width="960" alt="Bildschirmfoto 2020-06-11 um 15 23 59" src="https://user-images.githubusercontent.com/2278756/84390268-98613280-abf7-11ea-986f-9ffd4f4bdb5a.png">

https://dev.twitch.tv/docs/embed/video-and-clips/

**Comment by flowdee** [comment]
- https://wordpress.org/support/topic/need-update-21/
- https://secure.helpscout.net/conversation/1191399736/25762/
- https://secure.helpscout.net/conversation/1191592602/25770/

**Comment by webdj-agency** [comment]
the shortcode `[twitch ...]` feature is available in the PRO version so the appropriate bug is fixed in the PRO version's repo

**Comment by flowdee** [comment]
https://secure.helpscout.net/conversation/1192866907/25820/

**Comment by flowdee** [comment]
Fixed with release of v3.0.1
