### ISSUE TITLE
Offline streams are not displayed

### ISSUE THREAD

**Issue by webdj-agency** [flowdee/tomparisde-twitchtv-widget#37]
If all the streamers from the given streamer list are OFFLINE - the output shows "No Streams Found" message

**Comment by flowdee** [comment]
https://secure.helpscout.net/conversation/1459923963/34805?folderId=407335

**Comment by flowdee** [comment]
https://secure.helpscout.net/conversation/1471803948/35202?folderId=407335

**Comment by flowdee** [comment]
https://secure.helpscout.net/conversation/1474434231/35308/

**Comment by flowdee** [comment]
Fixed with v3.2.3
